#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Generador Word Avanzado
Crea documentos profesionales con estilos y formatos
"""

import os
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import pandas as pd

def generar_word_avanzado():
    """
        Genera documentos Word con estilos profesionales
            """
                print("=" * 60)
                    print("Generador Word Avanzado - Documentos Profesionales")
                        print("=" * 60)

                                archivo_datos = 'datos/productos.xlsx'

                                        if not os.path.exists(archivo_datos):
                                                print(f"Error: No se encontro {archivo_datos}")
                                                        print("Copia tu archivo Excel a datos/productos.xlsx")
                                                                return

                                                                        print(f"\nLeyendo {archivo_datos}...")
                                                                            datos = pd.read_excel(archivo_datos)
                                                                                os.makedirs('output', exist_ok=True)

                                                                                        for idx, row in datos.iterrows():
                                                                                                doc = Document()
                                                                                                        
                                                                                                                # Titulo principal
                                                                                                                        titulo = doc.add_heading(f"Catalogo #{idx+1}", level=0)
                                                                                                                                titulo.alignment = WD_ALIGN_PARAGRAPH.CENTER
                                                                                                                                        titulo_format = titulo.runs[0]
                                                                                                                                                titulo_format.font.color.rgb = RGBColor(31, 78, 121)
                                                                                                                                                        titulo_format.font.size = Pt(24)
                                                                                                                                                                titulo_format.font.bold = True
                                                                                                                                                                        
                                                                                                                                                                                # Linea separadora
                                                                                                                                                                                        doc.add_paragraph("" + "-" * 50)
                                                                                                                                                                                                
                                                                                                                                                                                                        # Nombre del producto
                                                                                                                                                                                                                nombre_p = doc.add_paragraph()
                                                                                                                                                                                                                        nombre_r = nombre_p.add_run(f"Producto: ")
                                                                                                                                                                                                                                nombre_r.font.bold = True
                                                                                                                                                                                                                                        nombre_r.font.size = Pt(12)
                                                                                                                                                                                                                                                nombre_p.add_run(str(row.get('Nombre', 'N/A')))
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                # Precio
                                                                                                                                                                                                                                                                        precio_p = doc.add_paragraph()
                                                                                                                                                                                                                                                                                precio_r = precio_p.add_run(f"Precio: ")
                                                                                                                                                                                                                                                                                        precio_r.font.bold = True
                                                                                                                                                                                                                                                                                                precio_r.font.size = Pt(12)
                                                                                                                                                                                                                                                                                                        precio_val = precio_p.add_run(f"${row.get('Precio', 'N/A')}")
                                                                                                                                                                                                                                                                                                                precio_val.font.color.rgb = RGBColor(0, 176, 80)
                                                                                                                                                                                                                                                                                                                        precio_val.font.bold = True
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                        # Descripcion
                                                                                                                                                                                                                                                                                                                                                desc_p = doc.add_paragraph()
                                                                                                                                                                                                                                                                                                                                                        desc_r = desc_p.add_run(f"Descripcion: ")
                                                                                                                                                                                                                                                                                                                                                                desc_r.font.bold = True
                                                                                                                                                                                                                                                                                                                                                                        desc_r.font.size = Pt(12)
                                                                                                                                                                                                                                                                                                                                                                                desc_p.add_run(str(row.get('Descripcion', 'N/A')))
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                # Pie de pagina
                                                                                                                                                                                                                                                                                                                                                                                                        doc.add_paragraph()
                                                                                                                                                                                                                                                                                                                                                                                                                footer = doc.add_paragraph("Documento generado automaticamente")
                                                                                                                                                                                                                                                                                                                                                                                                                        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
                                                                                                                                                                                                                                                                                                                                                                                                                                footer_run = footer.runs[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                        footer_run.font.size = Pt(9)
                                                                                                                                                                                                                                                                                                                                                                                                                                                footer_run.font.italic = True
                                                                                                                                                                                                                                                                                                                                                                                                                                                        footer_run.font.color.rgb = RGBColor(128, 128, 128)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Guardar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nombre_salida = f"output/catalogo_avanzado_{idx+1:04d}.docx"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.save(nombre_salida)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"✓ Creado: {nombre_salida}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"\n" + "=" * 60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Listo! Se crearon {len(datos)} catalogos profesionales")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"Ubicacion: carpeta output/")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("=" * 60 + "\n")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        generar_word_avanzado()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
